import "./globals.css";
import SideNav from "./components/SideNav";

export const metadata = {
  title: "File Sharing App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="layout-body">
        
        {/* TOP MENU / NAVBAR */}
        <header className="layout-header">
          <SideNav />
        </header>

        {/* PAGE CONTENT */}
        <main className="layout-content">
          {children}
        </main>

      </body>
    </html>
  );
}
